### ISSUE TITLE
verbose does not work

### ISSUE THREAD

**Issue by e7dal** [e7dal/bubble3#12]
root@1c5bc8d0c787:/opt/bubble_test/ndw# bubble -v 10000 -b 10 pull
BubbleCli:here!
BubbleCli:config
  stuff:
{'bubble_lib_dir': '/usr/local/lib/python3.6/site-packages/bubble3',
 'logfile': '',
 'parent': None,
 'verbose': 10000,
 'verbose_bar': 10}
Hi there,
i'm a inside a Bubble,
my name is BubbleCli.

a.k.a: API in the middle

Helps you where two of your "complex" services don't play well with each other.
And where you need get some information from A to B,
while transforming or filtering the information,  simply put:
 >>>A:pull>>>bubble:transform>>>B:push>>>
consider me your "small information" manager in between your big data and ESB(s),ETL(s).

Create a bubble, make the information flow and start bubbling .o.O.o.

Traceback (most recent call last):
  File "/usr/local/bin/bubble", line 11, in <module>
    sys.exit(cli())
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 1063, in invoke
    Command.invoke(self, ctx)
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/bubble3/cli.py", line 350, in cli
    verbose_bar=barverbose)
  File "/usr/local/lib/python3.6/site-packages/bubble3/cli.py", line 102, in __init__
    verbosity=2)
  File "/usr/local/lib/python3.6/site-packages/bubble3/__init__.py", line 272, in say
    self._msg(msg=msg, stuff=stuff, verb='SAY', verbosity=verbosity)
  File "/usr/local/lib/python3.6/site-packages/bubble3/__init__.py", line 255, in _msg
    blog.info(**tl_item)
  File "/usr/local/lib/python3.6/site-packages/structlog/_base.py", line 176, in _proxy_to_logger
    args, kw = self._process_event(method_name, event, event_kw)
  File "/usr/local/lib/python3.6/site-packages/structlog/_base.py", line 136, in _process_event
    event_dict = proc(self._logger, method_name, event_dict)
  File "/usr/local/lib/python3.6/site-packages/structlog/dev.py", line 179, in __call__
    event = event_dict.pop("event")
KeyError: 'event'
exit
  stuff:
{'config_yaml': 'config/config.yaml',
 'dot_bubble': '.bubble',
 'gbc': <bubble3.Bubble object at 0x7f3795709e10>,
 'profiling': False,
 'stages': ['PROD', 'ACC', 'TEST', 'DEV', 'MOCK'],
 'start_arrow': <Arrow [2018-06-04T06:50:18.741817+00:00]>,
 'steps': ['pulled',
           'uniq_pull',
           'uniq_push',
           'push',
           'pushed',
           'store',
           'stats'],
 'storage_types': ['json', 'jsonl']}

**Comment by e7dal** [comment]
will print all verbose messages in a **safe format** as shell comments:
 print("###<<<",tl_item,"<<<")
